DELIMITER $ 

-- CREATE PROCEDURE `PROCEDURENAME`(USERNAMET CHAR(32))
-- BEGIN
-- END$

CREATE PROCEDURE `GET_USER_SESSION_ID`(USERNAMET CHAR(32))
BEGIN
	SELECT * FROM TAI_KHOAN 
    WHERE USERNAME = USERNAMET;
END$

CREATE PROCEDURE `LOGIN`(USERNAMET CHAR(32), PASSWORDT CHAR(32))
BEGIN
	SELECT * FROM TAI_KHOAN 
    WHERE USERNAME = USERNAMET
		AND PASSWORD = PASSWORDT;
END$

CREATE PROCEDURE `SET_USER_SESSION_ID`(USERNAMET CHAR(32), IDT VARCHAR(255))
BEGIN
	UPDATE TAI_KHOAN 
    SET USER_SESSION_ID = IDT
    WHERE USERNAME = USERNAMET;
END$

CREATE PROCEDURE `REGISTER`(USERNAMET CHAR(32), PASSWORDT CHAR(32), TEN_NGUOI_DUNGT VARCHAR(128))
BEGIN
	 INSERT INTO TAI_KHOAN(`USERNAME`, `PASSWORD`, `MA_LOP`, `MA_LOAI_TAI_KHOAN`) VALUE (USERNAMET, PASSWORDT, 1, 1);
     INSERT INTO NGUOI_DUNG(`USERNAME`,`TEN_NGUOI_DUNG`, `CAU_HOI_HIEN_TAI`, `DO_DOI`, `TIEN`, `KINH_NGHIEM`) VALUE (USERNAMET, TEN_NGUOI_DUNGT, 0, 50, 500, 0);
END$

CREATE PROCEDURE `FINDTAIKHOANNGUOIDUNGBYUSERNAME`(USERNAMET CHAR(32))
BEGIN
	 SELECT TK.USERNAME,
			TK.PASSWORD,
            LH.MA_LOP,
            LH.TEN_LOP,
            ND.MA_NGUOI_DUNG,
            ND.TEN_NGUOI_DUNG,
            ND.DO_DOI,
            ND.TIEN,
            ND.KINH_NGHIEM,
            ND.CAU_HOI_HIEN_TAI,
            LTK.MA_LOAI_TAI_KHOAN,
            LTK.TEN_LOAI_TAI_KHOAN
     FROM TAI_KHOAN TK JOIN NGUOI_DUNG ND ON TK.USERNAME = ND.USERNAME 
					   JOIN LOP_HOC LH ON TK.MA_LOP = LH.MA_LOP 
                       JOIN LOAI_TAI_KHOAN LTK ON TK.MA_LOAI_TAI_KHOAN = LTK.MA_LOAI_TAI_KHOAN
     WHERE TK.USERNAME = USERNAMET;
END$



CREATE PROCEDURE `CHANGECAUHOIBYUSERNAME`(USERNAMET CHAR(32))
BEGIN
	IF (SELECT DO_DOI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET) > 0 THEN
		UPDATE NGUOI_DUNG
		SET CAU_HOI_HIEN_TAI = (
			SELECT MA_CAU_HOI 
			FROM CAU_HOI 
			WHERE MA_LOP = (SELECT MA_LOP FROM TAI_KHOAN WHERE USERNAME = USERNAMET)
			ORDER BY RAND() LIMIT 1)
		WHERE USERNAME = USERNAMET;
	ELSE
		UPDATE NGUOI_DUNG
		SET CAU_HOI_HIEN_TAI = 1
		WHERE USERNAME = USERNAMET;
		END IF;
END$

CREATE PROCEDURE `SELECTCAUTRALOIBYUSERNAME`(USERNAMET CHAR(32), CAU_TRA_LOIT VARCHAR(256))
BEGIN
	IF ((
    SELECT CAU_TRA_LOI_DUNG FROM CAU_HOI 
    WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET)) = CAU_TRA_LOIT)
    THEN
		UPDATE NGUOI_DUNG
        SET
			TIEN = TIEN + (SELECT TIEN_CAU_HOI FROM CAU_HOI WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET)),
            KINH_NGHIEM = KINH_NGHIEM + (SELECT KINH_NGHIEM_CAU_HOI FROM CAU_HOI WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET))
		WHERE USERNAME = USERNAMET;
        
        SELECT TIEN_CAU_HOI, KINH_NGHIEM_CAU_HOI 
        FROM CAU_HOI WHERE MA_CAU_HOI = (
			SELECT CAU_HOI_HIEN_TAI 
            FROM NGUOI_DUNG 
            WHERE USERNAME = USERNAMET);
    END IF;
    IF (SELECT DO_DOI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET) > 0 THEN
		UPDATE NGUOI_DUNG
		SET DO_DOI = DO_DOI - 1
		WHERE USERNAME = USERNAMET;
	END IF;
END$

CREATE PROCEDURE `GETCAUHOIHIENTAIBYUSERNAME`(USERNAMET CHAR(32))
BEGIN
	SELECT MA_CAU_HOI,
		   NOI_DUNG_CAU_HOI
	FROM CAU_HOI
    WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET);
END$

CREATE PROCEDURE `GETCAUTRALOIBYUSERNAME`(USERNAMET CHAR(32))
BEGIN
	SELECT MA_CAU_HOI,
		   MA_CAU_TRA_LOI,
		   NOI_DUNG_TRA_LOI
	FROM CAU_TRA_LOI
    WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = USERNAMET);
END$

CREATE PROCEDURE `GETNOIDUNGSAUTRALOIBYMACAUTRALOI`(MACAUTRALOIT INT)
BEGIN
	SELECT NOI_DUNG_SAU_TRA_LOI
    FROM CAU_TRA_LOI
    WHERE MA_CAU_TRA_LOI = MACAUTRALOIT;
END$

DELIMITER ;

SELECT * FROM LOP_HOC;
SELECT * FROM TAI_KHOAN;
SELECT * FROM NGUOI_DUNG;
SELECT * FROM CAU_HOI;
SELECT * FROM LOAI_TAI_KHOAN;
SELECT * FROM CAU_TRA_LOI;

INSERT INTO LOP_HOC(`TEN_LOP`, `MIEU_TA`) VALUES ('LỚP TỰ HỌC', 'LỚP TỰ HỌC LÀ LỚP HỌC NHIỀU CHỦ ĐỀ, KHÔNG CHUYÊN VỀ CHỦ ĐỀ NÀO');
INSERT INTO LOP_HOC(`TEN_LOP`, `MIEU_TA`) VALUES ('CAO NGUYÊN TOÁN HỌC', 'CAO NGUYÊN TOÁN HỌC LÀ NƠI LƯU TRỮ TINH HOA CỦA TOÁN HỌC CƠ BẢN, NHỮNG NGƯỜI THẦY GIÁO TUYỆT VỜI ĐANG CƯ NGỤ Ở ĐÂY');
INSERT INTO LOAI_TAI_KHOAN(`TEN_LOAI_TAI_KHOAN`) VALUES ('NGƯỜI DÙNG');
INSERT INTO LOAI_TAI_KHOAN(`TEN_LOAI_TAI_KHOAN`) VALUES ('ADMIN');

-- CALL GET_USER_SESSION_ID('MRHAOMP2001'); 

CALL REGISTER('MRHAOMP2001', 'AA442666', 'HUỲNH NHỰT HÀO');
CALL FINDTAIKHOANNGUOIDUNGBYUSERNAME('MRHAOMP2001');
-- CÂU 1 LỚP 1
INSERT INTO `CAU_HOI` (`MA_LOP`, `NOI_DUNG_CAU_HOI`, `CAU_TRA_LOI_DUNG`, `TIEN_CAU_HOI`, `KINH_NGHIEM_CAU_HOI`) 
VALUES ('1', 'BẠN ĐANG ĐÓI! HÃY TÌM THỨ GÌ ĐÓ ĂN TRƯỚC KHI TIẾP TỤC HỌC.', '0', '0', '0');
INSERT INTO `CAU_TRA_LOI` (`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES ('1', 'BẠN ĐANG ĐÓI!', 'HÃY ĐI ĂN TRƯỚC!');

-- CÂU 2 LỚP 1
INSERT INTO CAU_HOI(`MA_LOP`, `NOI_DUNG_CAU_HOI`, `CAU_TRA_LOI_DUNG`, `TIEN_CAU_HOI`, `KINH_NGHIEM_CAU_HOI`) 
VALUES (1, 'MỘT CON RÙA BÒ NGANG VÀ HỎI BẠN: 14 + 2*8^2 BẰNG BAO NHIÊU, BẠN SẼ TRẢ LỜI NHƯ THẾ NÀO?', '142', 10, 1);

INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (2, '142', 'CON RÙA KHEN BẠN HAY, SAU ĐÓ NÓ TIẾP TỤC CUỘC ĐUA CỦA NÓ');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (2, '143', 'CON RÙA CHÊ BẠN KHÔNG THÔNG MINH, SAU ĐÓ NÓ TIẾP TỤC CUỘC ĐUA CỦA NÓ');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (2, '144', 'CON RÙA LÚ NHƯ CON CÚ, BẠN ĐÃ SAI');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (2, '145', 'CON RÙA DI CHUYỂN VỚI TỐC ĐỘ SIÊU THANH DO BẠN ĐÃ TÍNH SAI, BẠN ĐÃ SAI!');

-- CÂU 3 LỚP 1
INSERT INTO CAU_HOI(`MA_LOP`, `NOI_DUNG_CAU_HOI`, `CAU_TRA_LOI_DUNG`, `TIEN_CAU_HOI`, `KINH_NGHIEM_CAU_HOI`) 
VALUES (1, 'MỘT CÔ GIÁO HÓA HỌC HỎI BẠN GIÁ TRỊ CỦA BIỂU THỨC 8.(A2 + B2) + 100 TẠI A = 3, B = 4.', '300', 15, 2);

INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (3, '200', 'PHÒNG CỦA CÔ GIÁO BỊ NỔ, MẶT GIÁO ĐEN THUI DO BẠN TÍNH SAI SỐ THUỐC CẦN THÊM VÀO. BẠN ĐÃ SAI!');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (3, '300', 'CÔ GIÁO CHO BẠN 1 VIÊN KẸO :D');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (3, '400', 'CÔ GIÁO ĐÔ CHỜI VÌ TÍNH TOÁN SAI THÀNH PHẦN THUỐC! BẠN ĐÃ SAI :D');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (3, '500', '"HỌC LỚP MẤY RỒI MẬY?" - CÔ GIÁO SAID');


-- CÂU 4 LỚP 2
 INSERT INTO CAU_HOI(`MA_LOP`, `NOI_DUNG_CAU_HOI`, `CAU_TRA_LOI_DUNG`, `TIEN_CAU_HOI`, `KINH_NGHIEM_CAU_HOI`) 
VALUES (2, 'TÌM GIÁ TRỊ CỦA X THỎA MÃN: {23 + [1 + (3 – 1)2]} : X = 13', '1', 30, 3);

INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (4, '1', 'BẠN ĐÚNG');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (4, '2', 'BẠN SAI');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (4, '3', 'BẠN SAI');
INSERT INTO CAU_TRA_LOI(`MA_CAU_HOI`, `NOI_DUNG_TRA_LOI`, `NOI_DUNG_SAU_TRA_LOI`) 
VALUES (4, '0', 'BẠN SAI');

CALL CHANGECAUHOIBYUSERNAME('MRHAOMP2001');
-- SELECT MA_CAU_HOI FROM CAU_HOI ORDER BY RAND() LIMIT 1;

SELECT CAU_TRA_LOI_DUNG FROM CAU_HOI WHERE MA_CAU_HOI = (SELECT CAU_HOI_HIEN_TAI FROM NGUOI_DUNG WHERE USERNAME = 'MRHAOMP2001');
CALL SELECTCAUTRALOIBYUSERNAME('MRHAOMP2001', '142');
CALL GETCAUHOIHIENTAIBYUSERNAME('MRHAOMP2001');
CALL GETCAUTRALOIBYUSERNAME('MRHAOMP2001');
CALL GETNOIDUNGSAUTRALOIBYMACAUTRALOI(2);